---

- name: configure | Ensure tor configuration
  ansible.builtin.template:
    src: torrc.j2
    dest: /etc/tor/torrc
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart tor
