---

- name: Sysinfo
  ansible.builtin.include_tasks: sysinfo.yml
  tags: tor:sysinfo

- name: Install
  ansible.builtin.include_tasks: install.yml
  tags: tor:install

- name: Enable
  ansible.builtin.include_tasks: enable.yml
  tags: tor:enable

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  tags: tor:configure
