---

- name: sysinfo | System details
  ansible.builtin.debug:
    msg: "{{ tor_sysinfo_item }}"
  with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  loop_control:
    loop_var: tor_sysinfo_item
